### ISSUE TITLE
Can run tests twice using shortcuts

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#20] opened 2018-04-09 19:44 UTC
I _think_ I can run the tests twice whilst using the shortcuts. The console is then populated with an amalgamation of all of these runs.

Not really a problem, just thought I'd mention it :-).

**Comment by twifty** [comment] 2018-04-09 19:46
which shortcut?

**Comment by Gert-dev** [comment] 2018-04-09 20:01
Sorry, should have mentioned that: `ctrl-alt-t` to run all tests. Though, I can also run tests twice using other shortcuts such as `ctrl-alt-f`

**Comment by twifty** [comment] 2018-04-10 10:13
I can't reproduce this one.

`ctrl-alt-t` should run the test suite(s) selected in the dropdown, if none are selected it reverts to phpunit's normal behaviour. `ctrl-alt-f` should run tests for the current file.

`ctrl-alt-c` is very similar to the `f`, but it runs test for only the class under the cursor. This is for those rare instances when somebody adds two or more test classes to the same file.

Are you seeing duplicate results in the tree or results of test which were not supposed to run?

**Comment by Gert-dev** [comment] 2018-04-10 15:43
Whilst PHPUnit is running, you can trigger it to run a second time, whilst the first one has not completed yet. The tests tree seems to handle it properly, but I see duplicate and overlapping output in the terminal. I can reproduce this by very rapidly pressing `ctrl-alt-t` twice.

**Comment by twifty** [comment] 2018-04-10 16:04
Ahh, understand. OK, I'll add a flag to prevent this.

**Comment by twifty** [comment] 2018-04-10 17:07
Fixed in 0.0.21

**Closed by twifty** 2018-04-10 17:07 UTC
Labels: bug
